### PR TITLE
Support typescript

### PR DESCRIPTION
**Pull request by woodser**
Supersedes #93

To test this PR:

1. `./bin/build_dist.sh`
2. `npm run test -- --grep "Sample code demonstration"` which runs TestSampleCode.ts

### CODE REVIEW

**Comment by Janaka-Steph** [comment]
The intention is to emit types but keep JS files? Why not converting every files to TS?

**Comment by woodser** [comment]
> The intention is to emit types but keep JS files? Why not converting every files to TS?

The library files themselves are written in JS, not TS. Are you suggesting to rewrite the library files in native TS?

In addition to being a huge effort, it shouldn't be necessary, since the final types are emitted.

But I may be missing something and I'm open to any suggestions. Thanks.

**Comment by Janaka-Steph** [comment]
But you don't benefit from type checking when types are separated like that. It's only useful for the consumer right?

**Comment by woodser** [comment]
> But you don't benefit from type checking when types are separated like that. It's only useful for the consumer right?

Yes it's only useful for the consumer. Ideally the entire library would be typescript, I think.

**Comment by Janaka-Steph** [comment]
Yes would be better. Maybe can try this tool or similar to do the boring work and then replacing with better types little by little https://github.com/airbnb/ts-migrate

**Comment by Janaka-Steph** [comment]
There is a bounty for that task https://bounties.monero.social/posts/80/1-200m-typescript-support-of-monero-javascript-library

**Comment by woodser** [comment]
Rebased on master.

I think a good next step is to start renaming .js files to .ts and add typing information to the method signatures.

**Comment by Janaka-Steph** [comment]
Maybe worth a try https://github.com/Bartmr/convert-js-to-ts

**Comment by hundehausen** [comment]
Hey @woodser are you planning on renaming the project to **monero-typescript**, when this project is done? :D

**Comment by woodser** [comment]
I was considering that, or maybe monero-ts? :)

**Comment by hundehausen** [comment]
monero-ts is a great choice!

**Comment by everoddandeven** [comment]
Hi, I'm also working on a file conversion from javascript to typescript. Maybe I can give you a hand to complete the job.

**Comment by woodser** [comment]
Hey thanks for the offer @everoddandeven. Fortunately this migration is mostly done; all tests are passing in typescript. I just need to finish final cleanup.

**Comment by hundehausen** [comment]
🚀 🚀 🚀 🚀

**Comment by hundehausen** [comment]
Congratulations, @woodser !

**Comment by woodser** [comment]
Thanks, but still need to get the documentation links working before I can release. :)

**Comment by woodser** [comment]
Ok, now it's released and published. :D

**Pull request merged**
